In [1]:
import numpy as np

In [ ]:
input_samples = 5
sample_size = 3
inp = np.arange(input_samples*sample_size).reshape((input_samples, sample_size))+1
# inp = np.arange(sample_size)+1

weights = np.array([
    [0.5, 0.25],
    [1, 1],
    [2, 2]])
print(weights.shape)
print("Input")
print(inp)
print("Weights")
print(weights)
print("Result")
print(np.dot(inp, weights))

(3, 2)
Input
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
Weights
[[0.5  0.25]
 [1.   1.  ]
 [2.   2.  ]]
Result
[[ 8.5   8.25]
 [19.   18.  ]
 [29.5  27.75]
 [40.   37.5 ]
 [50.5  47.25]]


In [19]:
n = 2
m = 3
p = 4
a = np.arange(n*m).reshape((m, n))
b = np.arange(p*n).reshape((n, p))
print(a, end="\n\n")
print(b, end="\n\n")
print(np.matmul(a,b))

[[0 1]
 [2 3]
 [4 5]]

[[0 1 2 3]
 [4 5 6 7]]

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


In [ ]:
def matmul(a, b):
    m = a.shape[0]
    p = b.shape[1]
    output = np.zeros(shape=(m, p))

    for i in range(m):
        for j in range(p):
            output[i, j] = np.sum(a[i]*b[:,j])

    return output

n = 2
m = 3
p = 3
a = np.arange(n*m).reshape((m, n))
b = np.arange(p*n).reshape((n, p))
print(a, end="\n\n")
print(b, end="\n\n")
print(matmul(a,b))


[[1 2]
 [3 4]
 [5 6]]

[[1 2 3]
 [4 5 6]]

[[ 9. 12. 15.]
 [19. 26. 33.]
 [29. 40. 51.]]


In [12]:
a = np.arange(6).reshape((2, 3))
print(a[:,0])

[0 3]
