In [2]:
import numpy as np

In [ ]:
input_samples = 5
sample_size = 3
inp = np.arange(input_samples*sample_size).reshape((input_samples, sample_size))+1
# inp = np.arange(sample_size)+1

weights = np.array([
    [0.5, 0.25],
    [1, 1],
    [2, 2]])
print(weights.shape)
print("Input")
print(inp)
print("Weights")
print(weights)
print("Result")
print(np.dot(inp, weights))

(3, 2)
Input
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
Weights
[[0.5  0.25]
 [1.   1.  ]
 [2.   2.  ]]
Result
[[ 8.5   8.25]
 [19.   18.  ]
 [29.5  27.75]
 [40.   37.5 ]
 [50.5  47.25]]
