In [1]:
import numpy as np

In [3]:
n_samp = 3
img_shape = (4,)
shape = (n_samp,) + img_shape
samples = np.arange(np.prod(shape)).reshape(shape)

In [4]:
in_features = np.prod(img_shape)
out_features = 4
kernel = np.arange(in_features*out_features).reshape((in_features, out_features))
kernel = kernel/np.max(kernel)
kernel

array([[0.        , 0.06666667, 0.13333333, 0.2       ],
       [0.26666667, 0.33333333, 0.4       , 0.46666667],
       [0.53333333, 0.6       , 0.66666667, 0.73333333],
       [0.8       , 0.86666667, 0.93333333, 1.        ]])

In [5]:
samples.reshape(-1, 4) @ kernel

array([[ 3.73333333,  4.13333333,  4.53333333,  4.93333333],
       [10.13333333, 11.6       , 13.06666667, 14.53333333],
       [16.53333333, 19.06666667, 21.6       , 24.13333333]])

In [ ]:
def dense(samples: np.ndarray, kernel: np.ndarray):
    if samples.ndim != 2 or kernel.ndim != 2:
        raise ValueError("Invalid samples or kernel dimensionality")
    out = np.zeros((samples.shape[0], kernel.shape[1]))

    for sample in samples:
        for j in range(kernel.shape[1]):
            for i in range(kernel.shape[0]):
                sample[]
            

    return out

In [15]:
def dot(sample, kernel):
    out = np.zeros(kernel.shape[1])
    for j in range(kernel.shape[1]):
        result = 0
        for i in range(kernel.shape[0]):
            result += kernel[i, j] * sample[i]
            

        out[j] = result
    return out

In [16]:
dense(samples, kernel)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
a = np.arange(3)
b = np.array([[1, 2],
              [3, 4],
              [5, 6]])
dot(a, b)

array([13., 16.])